### ISSUE TITLE
Consider doing releases on GitHub

### ISSUE THREAD

**Issue by mundschenk-at** [tribalNerd/multisite-robotstxt-manager#4]
Please consider doing releases on GitHub as well. The new WP.org plugin repository makes downloading previous version quite hard and when a version fails like #3, there is no easy way to downgrade again.

**Comment by tribalNerd** [comment]
Hello mundschenk-at,
Again, thanks for the tip. Version 1.0.7 is now available for download.

https://github.com/tribalNerd/multisite-robotstxt-manager/releases/tag/1.0.7

**Comment by mundschenk-at** [comment]
Thank you!
