### ISSUE TITLE
Changes to the network template are not saved

### ISSUE THREAD

**Issue by mundschenk-at** [tribalNerd/multisite-robotstxt-manager#5]
Any changes made to the network-wide template textbox are discarded when you click on "update settings".

**Comment by tribalNerd** [comment]
Hello again,
I'll correct that, however what you can do is save the robots.txt file first, then publish, and it will retain your changes.

**Comment by tribalNerd** [comment]
Hello mundschenk-at,
This has been corrected in Version 1.0.9, which has been released to both Git and Wp.

Chris

**Comment by mundschenk-at** [comment]
Thanks!
