### ISSUE TITLE
Do not delete data on plugin delete

### ISSUE THREAD

**Issue by mundschenk-at** [tribalNerd/multisite-robotstxt-manager#6]
When the plugin is deleted (even if for example there still is another copy in another folder), all data is lost. Since there already is an option to manually delete all the plugin's settings, uninstallation should not result in data loss.

(WordPress' official interface guidelines regarding uninstallation behavior are the subject of heavy discussion on a core ticket.)

**Comment by tribalNerd** [comment]
Hello mundschenk-at,
The uninstall.php file in Version 1.0.9 has been removed, until WP figures out what it's going to do.

Chris
