### ISSUE TITLE
error when trying to activate the plugin in Multisite Networks: Network Admin > Plugins Menu

### ISSUE THREAD

**Issue by tserofcj** [tribalNerd/multisite-robotstxt-manager#8]
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/html/bedrock/web/app/plugins/multisite-robotstxt-manager/inc/classes/class-plugin-activate.php on line 99 Error: Cannot use object of type WP_Error as array in /var/www/html/bedrock/web/app/plugins/multisite-robotstxt-manager/inc/classes/class-plugin-activate.php on line 99 Call Stack: 2.2455 13965952 1. Inpsyde\Wonolog\PhpErrorController->on_exception() /var/www/html/bedrock/vendor/inpsyde/wonolog/src/PhpErrorController.php:0

**Comment by asadowski10** [comment]
Hi team,

The wp_remote_get function can return a WP Error that you don't test : https://github.com/ChrisWinters/multisite-robotstxt-manager/blob/master/inc/classes/class-plugin-activate.php#L97
Therefore the plugin cannot be activated.

Could you plz fix this bug or do you want a pull request ?

Thanks,

**Comment by ChrisWinters** [comment]
Thanks @asadowski10 & @tserofcj for letting me know and pushing an update for it as well. I'll be updating the plugin at WordPress here shortly. ~Chris
